
# Build Stage
FROM node:20-alpine as build
WORKDIR /app
# Referência correta ao package.json sem .txt
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
